name: Email Reminder Scheduler

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes
  workflow_dispatch:       # manual run button

jobs:
  send-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run email scheduler
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          python mail.py
